# Generated by Django 4.2 on 2023-04-28 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fundraisers', '0003_alter_fundraiser_is_deleted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='payment_info',
            field=models.JSONField(default='None'),
            preserve_default=False,
        ),
    ]
