# Generated by Django 4.2 on 2023-04-28 19:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fundraisers', '0005_fundraiserlike'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fundraiserlike',
            name='amount_paid',
        ),
        migrations.RemoveField(
            model_name='fundraiserlike',
            name='amount_paid_currency',
        ),
        migrations.AddField(
            model_name='fundraiserlike',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
