# Generated by Django 4.2 on 2023-04-28 19:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fundraisers', '0006_remove_fundraiserlike_amount_paid_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fundraiserlike',
            options={'verbose_name': 'FundraiserLike'},
        ),
        migrations.CreateModel(
            name='FundraiserComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(help_text="User's comment on the fundraiser")),
                ('commented_at', models.DateTimeField()),
                ('is_deleted', models.BooleanField(default=False, help_text='Used for soft delete')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('fundraiser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fundraisers.fundraiser')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
