# Generated by Django 4.2 on 2023-04-29 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fundraisers', '0009_fundraiser_is_student_fundraiser_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fundraiser',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
