# Generated by Django 4.2 on 2023-04-29 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fundraisers', '0010_alter_fundraiser_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fundraiser',
            name='is_student',
        ),
    ]
