# Generated by Django 4.2 on 2023-05-05 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fundraisers', '0011_remove_fundraiser_is_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='fundraiser',
            name='about',
            field=models.TextField(default='Something something', verbose_name='Introduction regarding the fundraiser'),
            preserve_default=False,
        ),
    ]
