# Generated by Django 4.2 on 2023-05-05 11:14

from django.db import migrations
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('fundraisers', '0012_fundraiser_about'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fundraiser',
            name='amount_required',
            field=djmoney.models.fields.MoneyField(decimal_places=0, default_currency='INR', max_digits=5),
        ),
    ]
