# Generated by Django 4.2 on 2023-05-05 11:24

from django.db import migrations
import djmoney.models.fields
import djmoney.models.validators


class Migration(migrations.Migration):

    dependencies = [
        ('fundraisers', '0015_alter_fundraiser_amount_raised'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fundraiser',
            name='amount_raised',
            field=djmoney.models.fields.MoneyField(decimal_places=0, default_currency='INR', max_digits=5, validators=[djmoney.models.validators.MaxMoneyValidator(10000)]),
        ),
    ]
