# Generated by Django 4.2 on 2023-05-05 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fundraisers', '0018_alter_fundraiser_amount_raised_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fundraiser',
            name='about',
            field=models.TextField(error_messages={'blank': 'About field cannot be blank'}, verbose_name='Introduction regarding the fundraiser'),
        ),
        migrations.AlterField(
            model_name='fundraiser',
            name='details',
            field=models.TextField(error_messages={'blank': 'Fundraiser details are required.', 'required': 'Fundraiser details are required'}, verbose_name='Details regarding the fundraiser'),
        ),
        migrations.AlterField(
            model_name='fundraiser',
            name='name',
            field=models.CharField(error_messages={'blank': 'Fundraiser name is required.', 'required': 'Fundraiser name is required'}, max_length=120, verbose_name='Name of the fundraiser'),
        ),
    ]
