# Generated by Django 4.2 on 2023-05-18 05:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fundraisers', '0020_alter_fundraiser_uuid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donation',
            name='user',
        ),
    ]
